### ISSUE TITLE
Communication protocol changed a lot

### ISSUE THREAD

**Issue by CReimer** [Mollayo/Shelly-Dimmer-2-Reverse-Engineering#1] opened 2021-02-20 19:20 UTC
Have you ever tried to figure out what exactly changed after version 1.8.4?

Something is definitely different with the start marker. Because the serial output is flooded with errors about it.

I'll keep at it. But right now I don't have any clue what's going on.

**Comment by Mollayo** [comment] 2021-02-20 19:27
What do you mean by "start marker"

**Comment by Mollayo** [comment] 2021-02-20 19:28
And which file are you using ? serialSniffer.ino or the other ?

**Comment by CReimer** [comment] 2021-02-20 19:30
I see this message a lot after applying power. And I cannot open the webinterface. Like in your not_booting_poperly.jpg
https://github.com/Mollayo/Shelly-Dimmer-2-Reverse-Engineering/blob/master/fakeSTM32.ino#L187

I'm using a slightly modified fakeSTM32.ino. Had to make it work on my Arduino Due

**Comment by CReimer** [comment] 2021-02-20 19:32
Tried 1.8.4 before and everything worked as it should. I'm now at 1.8.5 and communication seems to be completely different

**Comment by Mollayo** [comment] 2021-02-20 19:41
It works for all the firmwares that are available here: https://github.com/Mollayo/Shelly-Dimmer-2-Reverse-Engineering/tree/master/shelly%20stock%20firmware.

The last firmware I have tried was the version 1.8.4. So it could be that the latest firmware (i.e. 1.8.5) works with a different protocol.

**Comment by CReimer** [comment] 2021-02-20 19:44
Yes that seems to be the case. Unfortunately 1.8.4 doesn't have no-neutral wire support, for that I need 1.9.x
But thanks, this answers my question

**Comment by Mollayo** [comment] 2021-02-20 19:49
I believe you can use the no-neutral wire configuration with previous firmwares. At least, it works for me. But it doesn't support the Shelly bypass. I use capacitors instead.

**Comment by CReimer** [comment] 2021-02-20 20:04
Ohh okay. I already installed Shelly bypass in all my lights. So I have to make it work somehow.
But it's good you mentioned serialSniffer I'll try that next. Compare some simple request between 1.8.4 and 1.8.5

**Comment by Mollayo** [comment] 2021-02-20 20:20
Sometimes, the serialSniffer does not work because it disturbs the serial connection between the ESP8266 and the STM32 (maybe by weakening the electrical signal). When the ESP8266 starts, it initialises the STM32 and send a frame to it. The STM32 is supposed to send back an acknowledgement frame. If it doesn't (because of the serial connection between the two microcontrollers being disturbed), then the ESP8266 is blocked and shows this wep page (https://github.com/Mollayo/Shelly-Dimmer-2-Reverse-Engineering/blob/master/not_booting_properly.jpg). This is a tricky part that blocked me for several days.

**Comment by Mollayo** [comment] 2021-02-21 08:22
I think I understand what's going on with the latest version of the Shelly firmware. I do not think that this new firmware is using a new protocol. When the STM32 receives the first frame from the ESP8266, it sends back the frame containing the number of the current version of the STM32 firmware. This is done with this code inside the function "processReceivedPacket()":
  if (payload_cmd == CMD_GET_VERSION)
  {
    Serial.printf("dimmer: received packet %s\n", hexToStr(payload,payload_size));
    Serial.printf("Get version\n");
    // Send the packet
    uint8_t payload[]={0x35,0x02};
    sendCommand(payload_cmd, payload, sizeof(payload));
  }

If the STM32 sends the version number of an old firmware (0x35,0x02 in the code above), the ESP8266 will try to send the new version of the firmware to update the STM32. And this causes the errors you see. So the solution is the find the number for this new firmware. And everything should come back to normal.

**Comment by Mollayo** [comment] 2021-02-21 09:11
And one simple way to get the version number of the latest STM32 firmware is to flash this custom firmware (https://github.com/Mollayo/Shelly-Dimmer-2) to your "Shelly Dimmer 2" device. You can then access to the device using telnet and display the version number of the STM32 device. Before flashing with this custom firmware, your Shelly device should be updated with the latest Shelly firmware so that the STM32 has the latest firmware.

**Comment by Mollayo** [comment] 2021-02-21 10:50
I just checked myself with the Shelly firmware 1.9.4. I can confirm that this new STM32 firmware uses the same protocol. And the version number is 0x42,0x02. So if you replace "0x35,0x02" by "0x42,0x02" in the file fakeSTM32.ino, it should work again.

**Comment by CReimer** [comment] 2021-02-21 13:55
Thanks a lot.
By listening into the serial communication I figured out a lot. I have an Arduino sketch now which makes all communication human readable

I was comparing with this https://github.com/jamesturton/shelly-dimmer-stm32/blob/main/COMMUNICATION.md
But soon I figured out that there are some grave differences. e.g. James uses 0x01 as Switch Command. No wonder it refuses to work with Tasmota.
There are some other small differences but mostly it's the 0x01/0x11 mixup and 0x02=>0x01 and 0x03=>0x02 downshifting

As for the versioning following James' scheme

ESP 1.8.4 => STM 2.53
ESP 1.8.5 => STM 2.53
ESP 1.9.0 => STM 2.63
ESP 1.9.3 => STM 2.63
ESP 1.9.4 => STM 2.66
ESP 1.9.5 => STM 3.5

Communication hasn't changed at all.

**Comment by CReimer** [comment] 2021-02-21 13:56
I intend to fix Tasmota send them a pull request and provide a fixed version of COMMUNICATION.md

**Comment by Mollayo** [comment] 2021-02-21 15:31
> Thanks a lot.
> By listening into the serial communication I figured out a lot. I have an Arduino sketch now which makes all communication human readable
> 
> I was comparing with this https://github.com/jamesturton/shelly-dimmer-stm32/blob/main/COMMUNICATION.md
> But soon I figured out that there are some grave differences. e.g. James uses 0x01 as Switch Command. No wonder it refuses to work with Tasmota.
> There are some other small differences but mostly it's the 0x01/0x11 mixup and 0x02=>0x01 and 0x03=>0x02 downshifting
> 
> As for the versioning following James' scheme
> 
> ESP 1.8.4 => STM 2.53
> ESP 1.8.5 => STM 2.53
> ESP 1.9.0 => STM 2.63
> ESP 1.9.3 => STM 2.63
> ESP 1.9.4 => STM 2.66
> ESP 1.9.5 => STM 3.5
> 
> Communication hasn't changed at all.

I think jamesturton is using a completely different protocol for his own version of the STM32 firmware (https://github.com/jamesturton/shelly-dimmer-stm32). And this version only works with Tasmota. This is currently not possible to use the Shelly version of the STM32 firmware in Tasmota.

What is your goal ? Do you want to use Tasmota for your Shelly devices ? Or do you plan to
develop a custom firmware that uses the STM32 firmware from Shelly ?

**Comment by CReimer** [comment] 2021-02-21 17:25
I want to use Tasmota for my devices. jamesturton's stm32 firmware has problem when there's no neutral wire connected.
I already adapted Tasmota to work with the official stm32 firmware but for some reason I cannot dim >70%, without triggering some kind of recovery in Tasmota.

**Comment by Mollayo** [comment] 2021-02-21 18:15
This problem of tasmota recovering is not surprising to me. I have spent quite some time trying different settings with different bulbs on the Shelly Dimmer 2. My observations:
- There is a brightness value above which the Shelly device switches off and reboots. You can find this maximum brightness by starting from a small value and gradually increasing this value until the Shelly device reboots. This maximum value for halogen bulbs is about 70% and about 40% for LED bulbs. This value also depends on the power of the bulb.
- There's also the trailing/leading edge parameter to set. In some cases, the Shelly device overheats. This can be solved by changing this trailing/leading edge parameter and the brightness level. But you should always keep an eye on the internal temperature.
My conclusion is that the Shelly device requires many trials before it can run reliably, especially for LED bulbs.

**Comment by Mollayo** [comment] 2021-02-23 08:37
@CReimer : did you solve your problem ? Should I close this issue?

**Comment by CReimer** [comment] 2021-02-23 09:31
Not exactly. But this issue can be closed anyway. I'll continue tinkering with Tasmota, there must be a plausible reason, why Shelly's firmware can dim close to 100% an Tasmota can't. I suspect it has something to do with Tasmota's power saving feature. Next I want to try if disabling that helps in any way.

**Comment by Mollayo** [comment] 2021-02-23 10:01
I think the Shelly's firmware does not dim at 100 %. As I told you before, there's a maximum value for the brightness that depends on the type of the bulb. My guess is that the Shelly firmware finds this value through the calibration step. After this, when you put the dimming value at 100% in the web UI, the Shelly firmware uses the maximum dimming value found during the calibration. But the web UI shows the dimming value at 100%. The real dimming value (i.e. the one found from the calibration) is hidden during the user.

**Closed as completed** 2021-02-23 10:02 UTC
